plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

remote_theme: pages-themes/tactile@v0.2.0

relative_links:
  enabled: true
  collections: true

include:
  - index.md

title: Shahnawaz Ahmed
description: shahnawaz.ahmed95@gmail.com | [Google scholar](https://scholar.google.com/citations?user=2WJXw9YAAAAJ&hl=en) | GitHub:[quantshah](github.com/quantshah) | Twitter:[quantshah](http://twitter.com/quantshah)